version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: car_shop
    ports:
      - "5433:5432"
    container_name: docker-postgres-car-shop
