server:
  port: 8081

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/car_shop
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: car-shop-group
