DROP TABLE IF EXISTS caroptions, cars, completions, completionscaroptions, carmodels, customers, purchases CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE customers
(
	customerid UUID DEFAULT uuid_generate_v4 (),
  	firstname TEXT NOT NULL,
  	middlename TEXT NOT NULL,
  	lastname TEXT NOT NULL,
  	PRIMARY KEY (customerid)
);

CREATE TABLE caroptions
(
  	optionid UUID DEFAULT uuid_generate_v4 (),
  	optionname TEXT NOT NULL UNIQUE,
  	PRIMARY KEY (optionid)
);

CREATE TABLE completions
(
  	completionid UUID DEFAULT uuid_generate_v4 (),
  	completionname TEXT NOT NULL UNIQUE,
  	PRIMARY KEY (completionid)
);

CREATE TABLE completionscaroptions
(
  	completionid UUID,
  	optionid UUID,
  	FOREIGN KEY (completionid) REFERENCES completions (completionid) ON DELETE CASCADE,
  	FOREIGN KEY (optionid) REFERENCES caroptions (optionid) ON DELETE CASCADE,
  	PRIMARY KEY (completionid, optionid)
);

CREATE TABLE carmodels
(
	modelid UUID DEFAULT uuid_generate_v4 (),
	modelname TEXT NOT NULL,
  	completionid UUID,
  	PRIMARY KEY (modelid),
  	FOREIGN KEY (completionid) REFERENCES completions (completionid) ON DELETE CASCADE
);

CREATE TABLE cars
(
	carid UUID DEFAULT uuid_generate_v4 (),
  	vin TEXT NOT NULL UNIQUE,
  	modelid UUID,
  	PRIMARY KEY (carid),
  	FOREIGN KEY (modelid) REFERENCES carmodels (modelid) ON DELETE CASCADE
);

CREATE TABLE purchases
(
	purchaseid UUID DEFAULT uuid_generate_v4 (),
  	purchasenumber INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	customerid UUID,
  	carid UUID,
  	PRIMARY KEY (purchaseid),
  	FOREIGN KEY (customerid) REFERENCES customers (customerid) ON DELETE CASCADE,
  	FOREIGN KEY (carid) REFERENCES cars (carid) ON DELETE CASCADE
);