DROP TABLE IF EXISTS car_options, cars, completions, completions_car_options, car_models, customers, purchases CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE customers
(
	customer_id UUID DEFAULT uuid_generate_v4 (),
  	first_name TEXT NOT NULL,
  	middle_name TEXT NOT NULL,
  	last_name TEXT NOT NULL,
  	PRIMARY KEY (customer_id)
);

CREATE TABLE car_options
(
  	option_id UUID DEFAULT uuid_generate_v4 (),
  	option_name TEXT NOT NULL UNIQUE,
  	PRIMARY KEY (option_id)
);

CREATE TABLE completions
(
  	completion_id UUID DEFAULT uuid_generate_v4 (),
  	completion_name TEXT NOT NULL UNIQUE,
  	PRIMARY KEY (completion_id)
);

CREATE TABLE completions_car_options
(
  	completion_id UUID,
  	option_id UUID,
  	FOREIGN KEY (completion_id) REFERENCES completions (completion_id) ON DELETE CASCADE,
  	FOREIGN KEY (option_id) REFERENCES car_options (option_id) ON DELETE CASCADE,
  	PRIMARY KEY (completion_id, option_id)
);

CREATE TABLE car_models
(
	model_id UUID DEFAULT uuid_generate_v4 (),
	model_name TEXT NOT NULL,
  	completion_id UUID,
  	PRIMARY KEY (model_id),
  	FOREIGN KEY (completion_id) REFERENCES completions (completion_id) ON DELETE CASCADE
);

CREATE TABLE cars
(
	car_id UUID DEFAULT uuid_generate_v4 (),
  	vin TEXT NOT NULL UNIQUE,
  	model_id UUID,
  	PRIMARY KEY (car_id),
  	FOREIGN KEY (model_id) REFERENCES car_models (model_id) ON DELETE CASCADE
);

CREATE TABLE purchases
(
	purchase_id UUID DEFAULT uuid_generate_v4 (),
  	purchase_number INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	customer_id UUID,
  	car_id UUID,
  	PRIMARY KEY (purchase_id),
  	FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE,
  	FOREIGN KEY (car_id) REFERENCES cars (car_id) ON DELETE CASCADE
);